- app/controllers/categories_controller.rb
- app/models/category.rb
- app/models/experience.rb
- app/views/categories/show.html.erb
- config/routes.rb
- spec/features/visitor_sees_all_experiences_assigned_to_a_single_category_spec.rb
- spec/features/visitor_views_all_experiences_spec.rb
- spec/support/factories.rb
Wrote the feature test and worked through some of the errors. This is a many to many relationship and I need some help with setting up these relationships and displaying them in the show.
@stovermc 
@somedayrainbows 
@slague
> User story 3 visitor sees all experiences assigned to a category

- app/controllers/categories_controller.rb
- app/models/category.rb
- app/views/categories/index.html.erb
- app/views/categories/show.html.erb
- app/views/experiences/index.html.erb
- config/routes.rb
- db/migrate/20170411223910_add_image_path_to_experiences.rb
- db/schema.rb
experiences table includes image path
first attemp to create vanity url paths
> Update experiences table

- app/controllers/categories_controller.rb
- app/models/category.rb
- config/routes.rb
vanitiy urls work AFTER categories/...
> update categories controller

- app/models/cart.rb
- app/models/cart_experience.rb
- app/models/experience.rb
cart experience now functioning with super delegator
> Adding items to the cart

- app/controllers/carts_controller.rb
- app/controllers/categories_controller.rb
- app/models/category.rb
- app/views/categories/show.html.erb
- config/routes.rb
- db/migrate/20170412191929_add_slugto_categories.rb
- db/schema.rb
- spec/features/visitor_sees_all_experiences_assigned_to_a_single_category_spec.rb
- spec/support/factories.rb
Updated show page for categories
> Vanity urls

- spec/features/visitor_sees_all_experiences_assigned_to_a_single_category_spec.rb
- spec/support/factories.rb
Updated factory girl and passed the visitor_sees_all_experiences_assigned_to_a_single_category
> Feature test

- app/controllers/carts_controller.rb
- app/controllers/experiences_controller.rb
- app/models/cart.rb
- app/models/cart_experience.rb
- app/models/category.rb
- db/schema.rb
> clean up stuff

- app/controllers/experiences_controller.rb
- app/views/carts/show.html.erb
- app/views/categories/show.html.erb
- app/views/experiences/index.html.erb
- app/views/experiences/show.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/features/cart/user_must_login_to_check_out_spec.rb
- spec/support/factories.rb
Two of three tests are passing, still need to add the logout button to the cart and test that items say in the cart when a visitor logs in
> Cart login or create account

- spec/features/cart/user_can_adjust_quantities_in_cart_spec.rb
> Cart experience logic

- app/views/carts/show.html.erb
- app/views/layouts/application.html.erb
- app/views/sessions/new.html.erb
- app/views/users/show.html.erb
- spec/features/cart/user_must_login_to_check_out_spec.rb
- spec/support/factories.rb
The function of the login, logout, checkout, and create account buttons are all working, however, the tests do not pass.
The views for login page were updated to only have email and password (Create Account retains name field)
> Feature test cart login logout

- app/assets/stylesheets/shop-homepage.css
- app/controllers/dashboard_controller.rb
- app/controllers/home_controller.rb
- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/features/home/visitors_can_view_a_home_page_spec.rb
> Continue styling

- app/controllers/sessions_controller.rb
- app/views/users/show.html.erb
fixed existing user log in through new user form
> fix remaining auth issue

- app/assets/stylesheets/shop-homepage.css
- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
updated nav links and other stuff in application.html.erb
> More style

- Gemfile
- app/models/order.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20170413223503_create_orders.rb
- db/schema.rb
- spec/features/orders/user_can_view_past_orders_spec.rb
- spec/support/factories.rb
> first orders test

- app/controllers/carts_controller.rb
- app/views/layouts/application.html.erb
- spec/features/cart/user_must_login_to_check_out_spec.rb
- spec/features/users/user_can_create_a_new_account_spec.rb
- spec/features/visitor_views_all_experiences_spec.rb
- spec/rails_helper.rb
- spec/support/authentication_helper.rb
- spec/support/cart_helper.rb
- spec/support/factories.rb
Tests are passing after all the merging, also created two modules to help test (check out my sweet git commit messages)
> Test clean up

- app/controllers/carts_controller.rb
- app/views/carts/show.html.erb
- spec/features/cart/user_can_add_items_to_cart_spec.rb
- spec/features/cart/user_can_adjust_quantities_in_cart_spec.rb
- spec/features/cart/user_can_remove_items_from_cart_spec.rb
- spec/features/visitor_views_all_experiences_spec.rb
Cleaned up cart tests (on the wrong branch, sorry) 
@somedayrainbows @NatBee @slague
> Viewing past orders

- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/orders/index.html.erb
- spec/features/orders/user_can_view_past_orders_spec.rb
- spec/support/authentication_helper.rb
- spec/support/factories.rb
Pass tests
added order controller, order model
updated related files
> 9 viewing past orders

- app/views/experiences/index.html.erb
- app/views/experiences/show.html.erb
- db/migrate/20170415165041_add_status_to_experiences.rb
- db/schema.rb
- db/seeds.rb
- spec/features/experiences/user_can_only_add_to_cart_active_experiences_spec.rb
- spec/support/factories.rb
*Added status to experiences table
*Updated factories to reflect schema change
*Updated seeds to reflect schema change
*Updated the experience index and show views
*All tests passing
> Add feature retire experiences

- app/views/carts/show.html.erb
- config/routes.rb
- spec/features/cart/user_can_check_out_spec.rb
- spec/support/factories.rb
Continued work on check out feature.
> 12 checking out

- app/controllers/application_controller.rb
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/carts/show.html.erb
- app/views/orders/index.html.erb
- spec/features/cart/user_can_check_out_spec.rb
* added create action and cart_reset method to 
Controller. 
* added method to order model for adding experiences
to a single order.
* modified checkout button to send a post to the 
orders#action.
* added flash message to create action in orders
Controller.
@somedayrainbows @NatBee @slague
> complete checkout functionality

- app/controllers/admin/dashboard_controller.rb
- app/controllers/application_controller.rb
- app/views/admin/dashboard/index.html.erb
- config/routes.rb
- spec/features/admin/only_admin_can_see_dashboard_spec.rb
- spec/features/admin/user_can_only_see_her_data_spec.rb
- spec/features/home/visitors_can_view_a_home_page_spec.rb
- spec/models/user_spec.rb
* Created admin namespacing
* Created admin/dashboard controller
* Created admin/dashboard index view
* Feature and model tests pass 
*Application controller method current_admin?
> Complete authenticated user security

- spec/features/admin/visitors_cannot_do_much_spec.rb
> Completes unauthenticated users security

- app/controllers/sessions_controller.rb
- spec/features/admin/admin_login_redirects_to_dashboard_spec.rb
- spec/features/admin/only_admin_can_see_dashboard_spec.rb
- spec/features/admin/visitors_cannot_do_much_spec.rb
* Updated sessions controller 
* Created and passed feature tests
> Complete admin logs in

- app/controllers/users_controller.rb
- app/views/users/_form.html.erb
- app/views/users/edit.html.erb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- db/seeds.rb
- spec/features/admin/admin_cannot_modify_users_spec.rb
- spec/features/users/user_can_create_a_new_account_spec.rb
* Updated users controller and routes to include edit
* Created partial for user form info 
* Added link to edit profile on the users show view
* Added an admin to seeds 
* Submit button = Create
* Created users edit view
* Feature tests pass
> Complete admin cannot modify users story

- app/controllers/admin/dashboard_controller.rb
- app/controllers/orders_controller.rb
- app/views/admin/dashboard/index.html.erb
- db/seeds.rb
- spec/features/admin/admin_can_see_a_listing_of_all_orders_spec.rb
* added status params to controller 
* added admin to order show
* built out dashboard index view
* added order seeds to seed file 
* First three tests complete
> Begin admin dashboard order functions(story 18)

- app/controllers/carts_controller.rb
- app/models/cart.rb
- spec/features/orders/user_can_view_past_orders_spec.rb
* moved logic for increasing/decreasing quantities
into cart.rb
* can longer decrease quantity below zero
@slague @NatBee @somedayrainbows
> Refactor cart controller

- app/views/admin/dashboard/index.html.erb
- app/views/categories/index.html.erb
- app/views/home/index.html.erb
* Added styling to admin dash
* Fixed links to featured experiences on homepage
> Fix styling on home page and admin dash

- app/models/order.rb
- app/views/orders/show.html.erb
- db/seeds.rb
- spec/features/admin/admin_sees_user_info_on_each_order.rb
* added a total_price method to order.rb
* updated order show view to include name and email 
* updated seeds to include experiences_orders
* all tests pass
> Completes admin views an individual order

- app/controllers/experiences_controller.rb
- app/models/user.rb
- app/views/carts/show.html.erb
- app/views/experiences/edit.html.erb
- app/views/experiences/show.html.erb
- app/views/users/_form.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- spec/features/orders/user_can_view_a_past_order_spec.rb
@NatBee @stovermc @somedayrainbows 
Final commit!
> Final fixes

- app/assets/stylesheets/shop-homepage.css
- app/views/experiences/index.html.erb
unable to add 100px max height to css for experiences
> Final touches
